# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-26 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='grade')),
                ('status', models.BooleanField(default=False)),
                ('submitime', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Papers', verbose_name='papid')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Student', verbose_name='stuid')),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=10)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.History', verbose_name='hisid')),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Quess')),
            ],
        ),
    ]
